# Import the relevant libraries

In [10]:
import numpy as np

# Declaring scalars, vectors and matrices

## Scalars

In [11]:
s = 5

In [12]:
s

5

## Vectors

In [13]:
v = np.array([5, -2, 4])

In [14]:
v

array([ 5, -2,  4])

## Matrices

In [15]:
m = np.array([[5, 12, 4], [-3, 0, 14]])

In [16]:
m

array([[ 5, 12,  4],
       [-3,  0, 14]])

## Data Types

In [17]:
type(m)

numpy.ndarray

In [19]:
s_array = np.array(5)

In [20]:
s_array

array(5)

In [21]:
type(s_array)

numpy.ndarray

## Data shapes

In [23]:
s_array.shape

()

In [24]:
m.shape

(2, 3)

# Working with tensor

## Creating a tensor

In [27]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [31]:
m2 = np.array([[8,9,7],[1,3,-5]])
m2

array([[ 8,  9,  7],
       [ 1,  3, -5]])

In [32]:
# Creating an array
t = np.array([m1,m2])

In [36]:
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 8,  9,  7],
        [ 1,  3, -5]]])

## Checking its shape

In [37]:
t.shape

(2, 2, 3)

## Manually creating a tensor

In [38]:
t_manual = np.array ([[[ 5, 12,  6], [-3,  0, 14]], [[ 8,  9,  7],[ 1,  3, -5]]])

In [39]:
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 8,  9,  7],
        [ 1,  3, -5]]])

# Matrices Manipulation

### Addition

In [42]:
m1 + m2

array([[13, 21, 13],
       [-2,  3,  9]])

### Difference

In [43]:
m1 - m2

array([[-3,  3, -1],
       [-4, -3, 19]])

## Transposing a matrix

In [44]:
a = np.array([[8,9,7],[1,3,-5]])

In [45]:
a

array([[ 8,  9,  7],
       [ 1,  3, -5]])

In [46]:
a.T

array([[ 8,  1],
       [ 9,  3],
       [ 7, -5]])

In [47]:
B = np.array([[5,2],[-3,6]])

In [49]:
B

array([[ 5,  2],
       [-3,  6]])

In [50]:
B.T

array([[ 5, -3],
       [ 2,  6]])

# Dot product

In [51]:
x = np.array([5,-2,7])
y = np.array([6,5,-8])

In [52]:
np.dot(x,y)

-36

## Scalar * Scalar

In [53]:
np.dot(6,5)

30

## Scalar * Vector

In [54]:
np.dot(x,8)

array([ 40, -16,  56])