## Train Test Split

### Import the relevant libraries

In [31]:
import numpy as np
from sklearn.model_selection import train_test_split

### Generate some data we are going split

In [32]:
a = np.arange(1,101)

In [33]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [34]:
b = np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

### Split the data

In [52]:
train_test_split(a)

[array([ 31,   7,  98,  16,   2,  38,  92,  60,  82,   1,  70,  99,  84,
         45,  77,  81,  29,  19,  52, 100,  40,  27,  86,  18,  44,  59,
         23,   5,  50,  56,  37,  30,  69,  43,  22,  61,  93,  53,  49,
          4,  15,  25,  36,  12,   6,  67,  80,  55,  75,  65,  46,  62,
         83,  94,  73,  35,  20,  26,  54,  58,  34,  42,   9,   3,  90,
         64,  88,  79,  76,  11,  89,  21,  95,  87,  32]),
 array([57, 13, 63, 71, 97,  8, 14, 91, 39, 47, 66, 17, 51, 78, 41, 74, 85,
        96, 48, 24, 10, 72, 28, 33, 68])]

In [53]:
a_train, a_test, = train_test_split(a, b, test_size = 0.2, random_state = 42)

ValueError: too many values to unpack (expected 2)

In [54]:
a_train.shape, a_test.shape

((80,), (20,))

In [55]:
a_train

array([ 93,  63,  75,  97,  49,  82,  55,  84,  45,  98,  22,   4,   1,
        59,  31,   5,  87,  79,  37,   2,  96,  53,  40,  25,  77,  52,
        33,  72,  56,  73,  42,  27,  30,  90,  66,  95,  12,  13,  38,
        23,  74,  39,  21,  94,  78,  18,  36,  48,  11,  91,  67,  80,
        24,  44,  99,  57, 100,  65,  17,  51,  26,  92,  71,  58,   7,
        70,  35,   9,  15,  43,  14,  41,  54,  28,   3,  86,  46,  50,
        10,  60])

In [56]:
a_test

array([47, 76, 29, 85,  8, 83, 34, 88, 69, 62, 19, 16, 68,  6, 20, 32, 64,
       81, 61, 89])

In [57]:
b_train, b_test = train_test_split(b, test_size = 0.2, random_state= 42)

In [50]:
b_train

array([556, 589, 527, 543, 570, 516, 541, 597, 510, 573, 512, 548, 586,
       529, 594, 506, 567, 566, 536, 517, 550, 535, 508, 596, 528, 520,
       582, 526, 563, 514, 525, 504, 518, 539, 509, 579, 507, 565, 537,
       590, 557, 600, 555, 544, 551, 568, 547, 569, 562, 598, 580, 542,
       559, 549, 599, 558, 576, 533, 595, 560, 564, 585, 538, 530, 502,
       553, 522, 503, 524, 588, 592, 575, 587, 583, 521, 561, 572, 515,
       593, 552])

In [45]:
b_test

array([526, 562, 527, 584, 512, 598, 510, 545, 569, 589, 570, 517, 577,
       501, 520, 518, 536, 507, 509, 550])